name: GH Actions CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions: { } # none

defaults:
  run:
    shell: bash -leo pipefail {0}

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'loiclefevre/standard-test2' }}

jobs:

  testpilot:
    permissions:
      contents: read
    name: GITHUB_OUTPUT tests
    runs-on: [ self-hosted, Linux, X64, OracleTestPilot ]
    strategy:
      fail-fast: false

    steps:
      - id: step_1
        name: step 1
        run: |
          echo "umask:"
          umask
          echo "${{ runner.temp }} directory files:"
          ls -lRa ${{ runner.temp }}
          echo "\$GITHUB_OUTPUT:"
          echo $GITHUB_OUTPUT
          echo "key1=value1" >> $GITHUB_OUTPUT
          echo "::add-mask::value2"
          echo "key2=value2" >> $GITHUB_OUTPUT
          echo "\$GITHUB_OUTPUT content:"
          cat $GITHUB_OUTPUT

      - id: step_2
        name: step 2
        run: |
          echo "${{ runner.temp }} directory files:"
          ls -lRa ${{ runner.temp }}
          echo "\$GITHUB_OUTPUT:"
          echo $GITHUB_OUTPUT
          echo "Values retrieved from previous step:"
          echo ${{steps.step_1.outputs.key1}}
          echo ${{steps.step_1.outputs.key2}}

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Java 21
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '21'
