name: GH Actions CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions: { } # none

defaults:
  run:
    shell: bash -leo pipefail {0}

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'loiclefevre/standard-test2' }}

jobs:

  testpilot:
    permissions:
      contents: read
    name: GITHUB_OUTPUT tests
    runs-on: [ self-hosted, Linux, X64, OCI ]
    strategy:
      fail-fast: false

    steps:
      - id: step_1
        name: step 1
        run: |
          id
          umask
          ls -l /home/ubuntu/actions-runner/_work/_temp
          echo $GITHUB_OUTPUT
          echo "key1=value1" >> $GITHUB_OUTPUT
          echo "::add-mask::value2"
          echo "key2=value2" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
          
      - id: step_2
        name: step 2
        run: |
          ls -l /home/ubuntu/actions-runner/_work/_temp
          echo $GITHUB_OUTPUT
          echo ${{steps.step_1.outputs.key1}}
          echo ${{steps.step_1.outputs.key2}}
